name: 'Build'
description: 'Build kernel and run it in VM'
inputs:
  repo-path:
    description: 'Path to repo'
    required: true
outputs:
runs:
  using: "composite"
  steps:
    - id: entry
      run: ${{ github.action_path }}/entry.sh ${{ inputs.repo-path }}
      shell: bash
